### ISSUE TITLE
Add Unity ElePHPant

### ISSUE THREAD

**Issue by cgrandval** [f500/elewant#244]
Add Unity ElePHPant that we can find in `afieldguidetoelephpants.net` from the Darkmira Tour PHP Conference.

**Comment by cookieguru** [comment]
It's already there:

![Screenshot showing Darkmira elePHPant](https://user-images.githubusercontent.com/1888809/65728222-2350cb80-e06f-11e9-83bb-0ddb7d117a77.png)

**Comment by cookieguru** [comment]
https://github.com/f500/elewant/blob/08c70f8daedd0f4b97d7c34d463950460ef826fe/src/Elewant/Webapp/Application/Resources/translations/herd.en.yml#L69
https://github.com/f500/elewant/blob/08c70f8daedd0f4b97d7c34d463950460ef826fe/src/Elewant/Herding/DomainModel/Breed/Breed.php#L56

**Comment by cgrandval** [comment]
Hi Tim, thanks for your answer. Sorry, I didn't see it before.

About the name, isn't it better to put the complete name of the conference? Darkmira Tour PHP or the ElePHPant name: Unity?

**Comment by cookieguru** [comment]
We could update it to `Darkmira PHP Tour` (makes more sense in English than "Darkmira Tour PHP").  It's a bit long, but not longer than `SunshinePHP Nexmo (L)`.

Unity is a little bit trickier.  I have found that a lot of people don't know about the name that the producer assigned them, so that would make it harder for people to find it.  Also some people name their elePHPants on their own.

**Comment by cgrandval** [comment]
As it's the exact name of the conference, don't think it's a good idea to change it to make more sense in English :-). The event is known with that name `Darkmira Tour PHP`.

**Comment by ramondelafuente** [comment]
Since the Elephpant is there, do you still want the name to be `Darkmira Tour PHP` or can we close this issue?

**Comment by cgrandval** [comment]
hi @ramondelafuente, if it's possible, likely better to put the name of the conference `Darkmira Tour PHP` :-)

**Comment by ramondelafuente** [comment]
Fixed by #249
