### ISSUE TITLE
Move inline JS to file(s) in assets folder

### ISSUE THREAD

**Issue by jaspernbrouwer** [f500/elewant#48]
>Except for the inline javascript. There's a (placeholder) file src/Elewant/FrontendBundle/Resources/assets/js/elewant.js, which is (emtpy, but) already used in Grunt. So I'd suggest to bind the events to to proper classes 🙂
>Also, we have jQuery, so no need to manually build anXMLHttpRequest 😉

**Comment by ramondelafuente** [comment]
This JS was a example in order to prototype the flow of herd management; explicitly _not_ tied to any framework to keep the choice free to whoever was planning to implement these views in the actual application.

I was going to re-write the example page after we had a nice working app. I don't want the example JS to leak into the files we will be using in production.

**Comment by ramondelafuente** [comment]
(I might not have been very clear that the `/example` is currently leading the way for a properly built production version)

**Comment by jaspernbrouwer** [comment]
Got it! 👍
